name: CD

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Export static files
        run: npm run export

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Deploy to S3
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            aws s3 sync ./out/ s3://${{ secrets.PROD_BUCKET_NAME }} --delete
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            aws s3 sync ./out/ s3://${{ secrets.DEV_BUCKET_NAME }} --delete
          fi
